import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { requireDidiAccess } from "@/lib/api/guard";

export async function POST(req: NextRequest) {
    const gate = requireDidiAccess(req, "operator", { csrf: true, action: "generate_image" });
    if (!gate.ok) return gate.response;

    try {
        const { text, modelSelection } = await req.json();

        if (!text) {
            return NextResponse.json({ error: "Missing text payload" }, { status: 400 });
        }

        const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");
        // Use the same model selected by user, or default to flash
        const model = genAI.getGenerativeModel({ model: modelSelection || 'gemini-2.5-flash' });

        const prompt = `Bạn là một chuyên gia thiết kế đồ hoạ vector (SVG). Dựa vào nội dung tài liệu tiếng Việt sau đây, hãy viết ra MỘT cấu trúc mã raw SVG (<svg>...</svg>) để minh hoạ trực quan và trừu tượng cho nội dung đó. Yêu cầu thiết kế hiện đại, isometric, hoặc flat design, màu sắc đa dạng bắt mắt hợp với phong cách công nghệ. Đặt width="1200" height="600" viewBox="0 0 1200 600".\n\nTUYỆT ĐỐI CHỈ TRẢ VỀ ĐOẠN CODE SVG THUẦN (KHÔNG BỌC TRONG \`\`\`svg hay html...\`\`\`, KHÔNG BỌC TRONG BẤT KỲ MARKDOWN NÀO, KHÔNG GIẢI THÍCH GÌ THÊM).\n\nNội dung:\n${text.substring(0, 5000)}`;

        const result = await model.generateContent(prompt);
        let svgCode = result.response.text().trim();

        // Remove markdown tags if AI hallucinated them
        if (svgCode.startsWith('```svg')) {
            svgCode = svgCode.substring(6).trim();
        } else if (svgCode.startsWith('```html')) {
            svgCode = svgCode.substring(7).trim();
        }
        if (svgCode.startsWith('```')) {
            svgCode = svgCode.substring(3).trim();
        }
        if (svgCode.endsWith('```')) {
            svgCode = svgCode.substring(0, svgCode.length - 3).trim();
        }

        return NextResponse.json({ svgCode, prompt: "SVG Code Auto-generated by Gemini" });

    } catch (error: any) {
        console.error("Image generation error:", error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
